import { StockQuote, CompanyProfile, NewsArticle, MarketNews } from './stockApi';

export const mockStockQuotes: Record<string, StockQuote> = {
  'AAPL': { c: 277.16, d: -0.39, dp: -0.14, h: 278.24, l: 275.99, o: 278.23, pc: 277.55, t: Date.now() / 1000 },
  'TSLA': { c: 429.35, d: 2.77, dp: 0.65, h: 432.93, l: 426.20, o: 427.63, pc: 426.58, t: Date.now() / 1000 },
  'NVDA': { c: 176.97, d: -3.29, dp: -1.83, h: 180.19, l: 176.53, o: 180.19, pc: 180.26, t: Date.now() / 1000 },
  'MSFT': { c: 490.92, d: 5.42, dp: 1.12, h: 492.63, l: 486.65, o: 487.88, pc: 485.50, t: Date.now() / 1000 },
  'META': { c: 644.63, d: 11.02, dp: 1.74, h: 646.25, l: 635.50, o: 635.50, pc: 633.61, t: Date.now() / 1000 },
  'GOOGL': { c: 319.14, d: -0.82, dp: -0.25, h: 326.85, l: 316.79, o: 323.16, pc: 319.95, t: Date.now() / 1000 },
  'AMZN': { c: 232.01, d: 2.85, dp: 1.24, h: 232.88, l: 230.22, o: 230.50, pc: 229.16, t: Date.now() / 1000 },
  'AMD': { c: 216.66, d: 2.42, dp: 1.13, h: 218.30, l: 214.02, o: 215.00, pc: 214.24, t: Date.now() / 1000 },
  'NFLX': { c: 107.50, d: 1.36, dp: 1.28, h: 107.94, l: 106.24, o: 106.68, pc: 106.14, t: Date.now() / 1000 },
  'DIS': { c: 104.41, d: 0.98, dp: 0.95, h: 104.74, l: 103.24, o: 103.69, pc: 103.43, t: Date.now() / 1000 },
  'SPY': { c: 600.25, d: 4.50, dp: 0.76, h: 602.15, l: 597.80, o: 598.90, pc: 595.75, t: Date.now() / 1000 },
  'QQQ': { c: 520.40, d: 7.20, dp: 1.40, h: 523.50, l: 515.80, o: 517.30, pc: 513.20, t: Date.now() / 1000 },
  'DIA': { c: 445.80, d: 2.30, dp: 0.52, h: 447.25, l: 444.20, o: 445.10, pc: 443.50, t: Date.now() / 1000 },
};

export const mockCompanyProfiles: Record<string, CompanyProfile> = {
  'AAPL': {
    country: 'US',
    currency: 'USD',
    exchange: 'NASDAQ',
    ipo: '1980-12-12',
    marketCapitalization: 3000000,
    name: 'Apple Inc.',
    phone: '14089961010',
    shareOutstanding: 15500,
    ticker: 'AAPL',
    weburl: 'https://www.apple.com/',
    logo: 'https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/AAPL.png',
    finnhubIndustry: 'Technology',
  },
  'TSLA': {
    country: 'US',
    currency: 'USD',
    exchange: 'NASDAQ',
    ipo: '2010-06-29',
    marketCapitalization: 770000,
    name: 'Tesla, Inc.',
    phone: '16506815000',
    shareOutstanding: 3170,
    ticker: 'TSLA',
    weburl: 'https://www.tesla.com/',
    logo: 'https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/TSLA.png',
    finnhubIndustry: 'Automobiles',
  },
  'NVDA': {
    country: 'US',
    currency: 'USD',
    exchange: 'NASDAQ',
    ipo: '1999-01-22',
    marketCapitalization: 1240000,
    name: 'NVIDIA Corporation',
    phone: '14084862000',
    shareOutstanding: 2453,
    ticker: 'NVDA',
    weburl: 'https://www.nvidia.com/',
    logo: 'https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/NVDA.png',
    finnhubIndustry: 'Semiconductors',
  },
};

export const mockMarketNews: MarketNews[] = [
  {
    category: 'technology',
    datetime: Date.now() / 1000 - 3600,
    headline: 'Tech Stocks Rally as AI Optimism Continues to Drive Market Sentiment',
    id: 1,
    image: 'https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: 'AAPL,MSFT,NVDA',
    source: 'Reuters',
    summary: 'Major technology stocks extended their gains today as investors remain bullish on artificial intelligence developments.',
    url: 'https://www.reuters.com/technology',
  },
  {
    category: 'market',
    datetime: Date.now() / 1000 - 7200,
    headline: 'Federal Reserve Signals Potential Interest Rate Cuts in Coming Months',
    id: 2,
    image: 'https://images.pexels.com/photos/259027/pexels-photo-259027.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: 'SPY,QQQ,DIA',
    source: 'Bloomberg',
    summary: 'The Federal Reserve hinted at possible rate cuts as inflation shows signs of cooling.',
    url: 'https://www.bloomberg.com/',
  },
  {
    category: 'company',
    datetime: Date.now() / 1000 - 10800,
    headline: 'NVIDIA Announces New AI Chip Breaking Performance Records',
    id: 3,
    image: 'https://images.pexels.com/photos/2582937/pexels-photo-2582937.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: 'NVDA',
    source: 'TechCrunch',
    summary: 'NVIDIA unveiled its latest GPU architecture, promising 3x performance improvements for AI workloads.',
    url: 'https://techcrunch.com/',
  },
  {
    category: 'economy',
    datetime: Date.now() / 1000 - 14400,
    headline: 'Consumer Spending Beats Expectations, Signaling Economic Resilience',
    id: 4,
    image: 'https://images.pexels.com/photos/210600/pexels-photo-210600.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: 'AMZN,WMT,TGT',
    source: 'Wall Street Journal',
    summary: 'Retail sales figures exceeded analyst forecasts, showing consumer confidence remains strong.',
    url: 'https://www.wsj.com/',
  },
  {
    category: 'technology',
    datetime: Date.now() / 1000 - 18000,
    headline: 'Apple Unveils Revolutionary VR Headset with Advanced Features',
    id: 5,
    image: 'https://images.pexels.com/photos/123335/pexels-photo-123335.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: 'AAPL',
    source: 'CNBC',
    summary: 'Apple introduces its next-generation Vision Pro with enhanced capabilities and competitive pricing.',
    url: 'https://www.cnbc.com/',
  },
  {
    category: 'automotive',
    datetime: Date.now() / 1000 - 21600,
    headline: 'Tesla Expands Gigafactory Operations to Meet Growing EV Demand',
    id: 6,
    image: 'https://images.pexels.com/photos/110844/pexels-photo-110844.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: 'TSLA',
    source: 'Reuters',
    summary: 'Tesla announced expansion plans for its manufacturing facilities amid record pre-orders.',
    url: 'https://www.reuters.com/business/autos-transportation',
  },
  {
    category: 'market',
    datetime: Date.now() / 1000 - 25200,
    headline: 'Stock Market Reaches New All-Time High Amid Tech Sector Strength',
    id: 7,
    image: 'https://images.pexels.com/photos/534216/pexels-photo-534216.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: 'SPY,QQQ',
    source: 'Financial Times',
    summary: 'Major indices hit record levels as technology stocks lead broad market rally.',
    url: 'https://www.ft.com/',
  },
  {
    category: 'technology',
    datetime: Date.now() / 1000 - 28800,
    headline: 'Microsoft Cloud Revenue Surges 30% Year-Over-Year',
    id: 8,
    image: 'https://images.pexels.com/photos/325229/pexels-photo-325229.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: 'MSFT',
    source: 'Bloomberg',
    summary: 'Microsoft reports strong quarterly results driven by Azure cloud platform growth.',
    url: 'https://www.bloomberg.com/',
  },
  {
    category: 'energy',
    datetime: Date.now() / 1000 - 32400,
    headline: 'Energy Prices Spike as OPEC Hints at Production Cuts',
    id: 9,
    image: 'https://images.pexels.com/photos/189525/pexels-photo-189525.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: 'XOM,CVX,CL',
    source: 'Wall Street Journal',
    summary: 'Crude futures climb after OPEC officials signal possible supply reductions later this year.',
    url: 'https://www.wsj.com/',
  },
  {
    category: 'market',
    datetime: Date.now() / 1000 - 36000,
    headline: 'Small-Cap Stocks Outperform as Rate-Cut Bets Rise',
    id: 10,
    image: 'https://images.pexels.com/photos/210607/pexels-photo-210607.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: 'IWM,RUT',
    source: 'Barron\'s',
    summary: 'Investors rotate into small caps on optimism the Fed will ease policy sooner than expected.',
    url: 'https://www.barrons.com/',
  },
  {
    category: 'finance',
    datetime: Date.now() / 1000 - 39600,
    headline: 'Private Equity Deal Volume Rebounds in Q2',
    id: 11,
    image: 'https://images.pexels.com/photos/4386464/pexels-photo-4386464.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: 'BX,CG,KKR',
    source: 'Financial Times',
    summary: 'Buyout firms close larger transactions as financing markets thaw and valuations stabilize.',
    url: 'https://www.ft.com/',
  },
  {
    category: 'travel',
    datetime: Date.now() / 1000 - 43200,
    headline: 'Airlines See Record Summer Bookings Despite Higher Fares',
    id: 12,
    image: 'https://images.pexels.com/photos/59519/pexels-photo-59519.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: 'DAL,UAL,AAL',
    source: 'Associated Press',
    summary: 'Carriers report packed schedules and improved margins as leisure demand stays resilient.',
    url: 'https://apnews.com/',
  },
  {
    category: 'technology',
    datetime: Date.now() / 1000 - 46800,
    headline: 'Chipmakers Say Supply Chain Pressures Are Easing',
    id: 13,
    image: 'https://images.pexels.com/photos/50711/board-electronics-computer-data-processing-50711.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: 'TSM,INTC,NVDA',
    source: 'The Verge',
    summary: 'Semiconductor executives point to normalized lead times and steadier pricing across nodes.',
    url: 'https://www.theverge.com/',
  },
  {
    category: 'crypto',
    datetime: Date.now() / 1000 - 50400,
    headline: 'Crypto Market Shrugs Off Regulatory Noise as Bitcoin Holds Gains',
    id: 14,
    image: 'https://images.pexels.com/photos/6770706/pexels-photo-6770706.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: 'BTC,ETH',
    source: 'CoinDesk',
    summary: 'Digital assets consolidate after a sharp rally, with traders eyeing upcoming ETF approvals.',
    url: 'https://www.coindesk.com/',
  },
  {
    category: 'economy',
    datetime: Date.now() / 1000 - 54000,
    headline: 'Housing Starts Climb as Builders Respond to Low Inventory',
    id: 15,
    image: 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: 'ITB,XHB',
    source: 'Bloomberg',
    summary: 'Residential construction picks up pace with incentives to offset higher mortgage rates.',
    url: 'https://www.bloomberg.com/',
  },
  {
    category: 'retail',
    datetime: Date.now() / 1000 - 57600,
    headline: 'Retailers Lean Into AI to Fix Inventory Gluts',
    id: 16,
    image: 'https://images.pexels.com/photos/5845715/pexels-photo-5845715.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: 'WMT,TGT,COST',
    source: 'Forbes',
    summary: 'Big-box chains deploy AI tools to forecast demand and reduce markdowns heading into holiday season.',
    url: 'https://www.forbes.com/',
  },
];

export const mockCompanyNews: NewsArticle[] = [
  {
    category: 'company',
    datetime: Date.now() / 1000 - 3600,
    headline: 'Company Reports Record Quarterly Earnings, Beats Analyst Expectations',
    id: 101,
    image: 'https://images.pexels.com/photos/534216/pexels-photo-534216.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: '',
    source: 'MarketWatch',
    summary: 'The company announced better-than-expected earnings results for the quarter.',
    url: 'https://www.marketwatch.com/',
  },
  {
    category: 'company',
    datetime: Date.now() / 1000 - 7200,
    headline: 'New Product Launch Drives Strong Pre-Order Numbers',
    id: 102,
    image: 'https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: '',
    source: 'TechCrunch',
    summary: 'Latest product release sees unprecedented customer demand and positive reviews.',
    url: 'https://techcrunch.com/',
  },
  {
    category: 'company',
    datetime: Date.now() / 1000 - 10800,
    headline: 'Strategic Partnership Announced with Industry Leader',
    id: 103,
    image: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=1200',
    related: '',
    source: 'Reuters',
    summary: 'Company forms strategic alliance to expand market reach and capabilities.',
    url: 'https://www.reuters.com/',
  },
];

export const mockGainers = [
  { symbol: 'NVDA', name: 'NVIDIA Corporation', quote: mockStockQuotes['NVDA'] },
  { symbol: 'AMD', name: 'Advanced Micro Devices', quote: mockStockQuotes['AMD'] },
  { symbol: 'NFLX', name: 'Netflix Inc', quote: mockStockQuotes['NFLX'] },
  { symbol: 'META', name: 'Meta Platforms Inc', quote: mockStockQuotes['META'] },
  { symbol: 'TSLA', name: 'Tesla Inc', quote: mockStockQuotes['TSLA'] },
];

export const mockLosers = [
  { symbol: 'DIS', name: 'Walt Disney Company', quote: mockStockQuotes['DIS'] },
];
